# Generated by Django 6.1 on 2026-08-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
