# Generated by Django 6.1 on 2026-09-26 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_user_ownership'),
        ('resumes', '0004_resume_user_ownership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='resume',
            name='ai_provider',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='source_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailored_resumes', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='resume',
            name='source_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailored_versions', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tailoring_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
