# Generated by Django 6.1 on 2026-09-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_updated_at'),
    ]

    operations = [
        # Hand-written rather than generated, deliberately.
        #
        # `makemigrations` on this machine also wants to rewrite the primary
        # keys of Resume and ResumeProfile from BigAutoField down to
        # AutoField, because the local interpreter resolves the implicit
        # `id` differently from the pinned Django 6.1 that CI and Render run.
        # Committing that would silently narrow every id column in
        # production on a live table. Only the field this feature adds is
        # wanted here; the primary keys stay as 0001_initial created them.
        migrations.AddField(
            model_name='resumeprofile',
            name='qualities',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]