"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str, default: bool = False) -> bool:
    """Read a boolean from the environment."""
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list:
    """Read a comma-separated list from the environment."""
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# ---------------------------------------------------------------------------
# Security
#
# Local development falls back to the in-repo defaults. In production these
# MUST come from the environment — never commit a real secret key.
# ---------------------------------------------------------------------------

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-development-only-do-not-use-in-production",
)

DEBUG = env_bool("DEBUG", default=True)

# The Vercel-hosted frontend must be allowed to call the API.
FRONTEND_ORIGIN = os.environ.get("FRONTEND_ORIGIN", "")

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS",
    default="localhost,127.0.0.1,[::1]",
)

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    default=(
        "http://localhost:5173,"
        "http://127.0.0.1:5173,"
        "http://localhost:3000,"
        "http://127.0.0.1:3000"
    ),
)

# Vercel preview deployments are served from a per-commit subdomain --
# match-score-<hash>-<team>.vercel.app -- so the origin of a branch preview
# cannot be hardcoded in CORS_ALLOWED_ORIGINS and it changes on every push.
# django-cors-headers matches this list as regular expressions, which is the
# only way to let previews talk to the API without disabling CORS for
# everything. Leave empty in production unless previews actually need it.
CORS_ALLOWED_ORIGINS_REGEX = env_list(
    "CORS_ALLOWED_ORIGINS_REGEX",
    default="",
)

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:5173,http://127.0.0.1:5173",
)

# Fold the single frontend origin into both lists when it is provided.
if FRONTEND_ORIGIN:
    if FRONTEND_ORIGIN not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(FRONTEND_ORIGIN)
    if FRONTEND_ORIGIN not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(FRONTEND_ORIGIN)

# Serve uploaded resumes. In production, MEDIA_URL is expected to be handled by
# the web server (or object storage) rather than by Django.
if DEBUG:
    _MEDIA_SERVE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'apps.applications',
    'apps.jobs',
    'apps.resumes',
    'apps.users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Django REST Framework
#
# SessionAuthentication is used instead of token auth so the browser holds
# an HttpOnly session cookie and no secret is readable from JavaScript.
# CSRF is enforced by Django for all unsafe methods on session requests.

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}


# ---------------------------------------------------------------------------
# AI / resume tailoring
#
# The provider is selected by name so no business logic ever needs to know which
# backend is in use. apps.ai.factory maps AI_PROVIDER onto a provider class, and
# the provider itself reads its own connection settings from here.
#
#   AI_PROVIDER=ollama     local Ollama daemon (development; no key needed)
#   AI_PROVIDER=gemini     Google AI Studio (hosted deployments)
#   AI_PROVIDER=fake       deterministic in-process double, for tests and CI
#
# Leaving AI_PROVIDER empty disables tailoring: the API then returns a clear
# "not configured" error rather than silently degrading to canned text.
# ---------------------------------------------------------------------------

AI_PROVIDER = (os.environ.get("AI_PROVIDER") or "").strip().lower()

OLLAMA_BASE_URL = (os.environ.get("OLLAMA_BASE_URL") or "").strip()

OLLAMA_MODEL = (os.environ.get("OLLAMA_MODEL") or "").strip()

#: Seconds to wait for the provider. Local models are slow on a cold start, so
#: this is generous; the API surfaces a timeout rather than hanging.
OLLAMA_TIMEOUT = int(os.environ.get("OLLAMA_TIMEOUT", "180"))

#: Low by default: tailoring must stay close to the source text, not improvise.
OLLAMA_TEMPERATURE = float(os.environ.get("OLLAMA_TEMPERATURE", "0.2"))

# --- Google Gemini -------------------------------------------------------
#
# The hosted provider. A hosted service cannot run an Ollama daemon, so this is
# what makes tailoring work on Render.
#
# There is deliberately **no** GEMINI_API_KEY. Users bring their own key from
# the UI and it is stored encrypted (see apps.users.crypto), so a deployment
# can never spend the owner's quota on someone else's behalf.

#: Defaults to gemini-3.8-flash in the provider. Overridable for anyone who
#: wants a different model or a newer one when it lands.
GEMINI_MODEL = (os.environ.get("GEMINI_MODEL") or "").strip()

GEMINI_TIMEOUT = int(os.environ.get("GEMINI_TIMEOUT", "120"))

GEMINI_TEMPERATURE = float(os.environ.get("GEMINI_TEMPERATURE", "0.2"))

# Default to ollama only when it is actually pointed at something, so local
# development works out of the box while a misconfigured deployment can never
# pretend an AI backend exists.
if not AI_PROVIDER and OLLAMA_BASE_URL and OLLAMA_MODEL:
    AI_PROVIDER = "ollama"


# CORS — credentials must be allowed for the session cookie to cross origins.
# CSRF_TRUSTED_ORIGINS is configured near the top of this file.
CORS_ALLOW_CREDENTIALS = True


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Development uses SQLite. When DATABASE_URL is present (Render, Railway, …)
# the project switches to that database, which is what production needs:
# SQLite on a container filesystem is not durable.

if os.environ.get("DATABASE_URL"):
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            os.environ["DATABASE_URL"],
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'

# WhiteNoise serves collected static files (admin CSS, for example) without a
# separate web server. It is required in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Uploaded resumes. Files are stored under media/<user_id>/.

MEDIA_URL = '/media/'

MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", BASE_DIR / 'media'))

# 10 MB ceiling for an uploaded master resume.
MAX_RESUME_UPLOAD_BYTES = 10 * 1024 * 1024

ALLOWED_RESUME_CONTENT_TYPES = {
    'application/pdf',
    'application/x-pdf',
}

ALLOWED_RESUME_EXTENSIONS = {'.pdf'}


# ---------------------------------------------------------------------------
# Session and CSRF cookies
#
# The SPA (Vercel) and the API (Render) are different registrable domains, so
# every request the browser makes is *cross-site*. That changes what the
# cookie attributes have to be:
#
#   SameSite=Lax  the browser refuses to attach the cookie to a cross-site
#                 fetch, even when the request sets `credentials: 'include'`.
#                 Signup succeeds, then every later call arrives anonymous --
#                 which looks exactly like a backend auth bug.
#   SameSite=None the cookie is sent cross-site, but browsers only accept it
#                 alongside `Secure`.
#
# So in production both flags are set together, and the test suite below
# pins that pairing so they cannot be separated later.
# ---------------------------------------------------------------------------

SESSION_COOKIE_SAMESITE = os.environ.get(
    "SESSION_COOKIE_SAMESITE",
    "Lax" if DEBUG else "None",
)
CSRF_COOKIE_SAMESITE = os.environ.get(
    "CSRF_COOKIE_SAMESITE",
    "Lax" if DEBUG else "None",
)


# ---------------------------------------------------------------------------
# Production hardening (applied only when DEBUG is off)
# ---------------------------------------------------------------------------

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    X_FRAME_OPTIONS = "DENY"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
