# Generated by Django 5.2 on 2026-09-30 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RESUME_UPLOADED', 'Resume uploaded'), ('MASTER_RESUME_CHANGED', 'Master resume changed'), ('JOB_ANALYSED', 'Job analysed'), ('JOB_ANALYSIS_FAILED', 'Job analysis failed'), ('TAILORING_GENERATED', 'Tailoring generated'), ('TAILORING_SAVED', 'Tailoring saved'), ('APPLICATION_CREATED', 'Application created'), ('APPLICATION_STATUS_CHANGED', 'Application status changed')], max_length=48)),
                ('object_type', models.CharField(blank=True, default='', max_length=32)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_user_time_idx'), models.Index(fields=['user', 'action'], name='activity_user_action_idx')],
            },
        ),
    ]
