# Generated by Django 5.2.17 on 2026-09-27 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="Provider slug, e.g. 'gemini'.", max_length=32)),
                ('encrypted_key', models.TextField(help_text='Fernet token. Never the plaintext key.')),
                ('key_hint', models.CharField(blank=True, default='', help_text="Masked hint such as 'AIza...4f2b'. Not a secret.", max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='uniq_user_provider_credential')],
            },
        ),
    ]
