# Generated by Django 5.2.17 on 2026-09-28 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_providercredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_setup',
            field=models.CharField(blank=True, default='', help_text="Chosen AI setup: 'ollama' (local) or 'gemini' (hosted).", max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='career_stage',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('fresher', 'Fresher'), ('professional', 'Professional')], default='', help_text='Student, fresher, or working professional.', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=0, help_text='Years of professional experience. 0 for students and freshers.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
