# Generated by Django 5.2.17 on 2026-09-29 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_ai_setup_userprofile_career_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('LOGIN_SUCCESS', 'Signed in'), ('LOGOUT', 'Signed out'), ('PASSWORD_CHANGED', 'Password changed'), ('SESSIONS_REVOKED', 'Other sessions signed out'), ('AI_KEY_CHANGED', 'API key updated')], max_length=32)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('is_current_session', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='secevent_user_time_idx')],
            },
        ),
    ]
