# Generated by Django 5.2 on 2026-09-30 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0005_job_source'),
        ('resumes', '0007_resumeprofile_qualities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('RESUME_TAILORING', 'Resume tailoring')], max_length=48)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('failure_category', models.CharField(blank=True, choices=[('CONFIGURATION', 'Misconfiguration'), ('PROVIDER_UNAVAILABLE', 'Provider unavailable'), ('PROVIDER_TIMEOUT', 'Provider timed out'), ('INVALID_RESPONSE', 'Unreadable model response'), ('VALIDATION_FAILED', 'Factual validation rejected the output'), ('INTERNAL', 'Unexpected failure')], default='', max_length=32)),
                ('error_code', models.CharField(blank=True, default='', max_length=48)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=32)),
                ('validation_status', models.CharField(blank=True, default='', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('result_resume', models.ForeignKey(blank=True, help_text='The artifact this run produced, once the user saved it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produced_by_ai_runs', to='resumes.resume')),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='jobs.job')),
                ('source_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_runs', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='airun_user_time_idx'), models.Index(fields=['user', 'operation'], name='airun_user_op_idx'), models.Index(fields=['status'], name='airun_status_idx')],
            },
        ),
    ]
