# Generated by Django 6.1 on 2026-08-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('company', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, choices=[('USE_MASTER', 'Use Master Resume'), ('TAILOR', 'Tailor Resume'), ('SKIP', 'Skip'), ('REVIEW', 'Review')], max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], default='NEW', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
