# Generated by Django 5.2.17 on 2026-09-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_user_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(default='generic', help_text="ATS this posting was read from, e.g. 'greenhouse'.", max_length=32),
        ),
    ]
