# Generated by Django 6.1 on 2026-09-26 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_job_user_ownership'),
        ('resumes', '0006_resume_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('APPLIED', 'Applied'), ('ASSESSMENT', 'Assessment'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='SAVED', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, help_text='Set when the candidate first submitted an application.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(help_text='The tracked job this application is for.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('tailored_resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='app_user_status_idx'), models.Index(fields=['user', '-updated_at'], name='app_user_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'job'), name='unique_application_per_user_job')],
            },
        ),
    ]
