# Generated by Django 5.2.17 on 2026-09-29 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_updates', models.BooleanField(default=True, help_text='Tell me when a job finishes analysing or tailoring.')),
                ('job_matches', models.BooleanField(default=True, help_text='Tell me when a new analysed job scores well against my resume.')),
                ('application_updates', models.BooleanField(default=True, help_text='Tell me when an application changes stage.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=16)),
                ('title', models.CharField(help_text='One line. The notification is skimmable from this alone.', max_length=120)),
                ('body', models.TextField(blank=True, default='', help_text='Optional second line of detail.')),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notif_unread_idx'), models.Index(fields=['user', '-created_at'], name='notif_user_time_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key__gt', '')), fields=('user', 'kind', 'dedupe_key'), name='uniq_notification_dedupe')],
            },
        ),
    ]
